/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConciergerieRouteImport } from './routes/conciergerie'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GestionProprieteRouteImport } from './routes/gestion-propriete'
import { Route as LocationSaisonniereRouteImport } from './routes/location-saisonniere'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesHousekeepingRouteImport } from './routes/services.housekeeping'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergerieRoute = ConciergerieRouteImport.update({
  id: '/conciergerie',
  path: '/conciergerie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GestionProprieteRoute = GestionProprieteRouteImport.update({
  id: '/gestion-propriete',
  path: '/gestion-propriete',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationSaisonniereRoute = LocationSaisonniereRouteImport.update({
  id: '/location-saisonniere',
  path: '/location-saisonniere',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesHousekeepingRoute = ServicesHousekeepingRouteImport.update({
  id: '/services/housekeeping',
  path: '/services/housekeeping',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conciergerie': typeof ConciergerieRoute
  '/contact': typeof ContactRoute
  '/gestion-propriete': typeof GestionProprieteRoute
  '/location-saisonniere': typeof LocationSaisonniereRoute
  '/zones': typeof ZonesRoute
  '/services/housekeeping': typeof ServicesHousekeepingRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conciergerie': typeof ConciergerieRoute
  '/contact': typeof ContactRoute
  '/gestion-propriete': typeof GestionProprieteRoute
  '/location-saisonniere': typeof LocationSaisonniereRoute
  '/zones': typeof ZonesRoute
  '/services/housekeeping': typeof ServicesHousekeepingRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conciergerie': typeof ConciergerieRoute
  '/contact': typeof ContactRoute
  '/gestion-propriete': typeof GestionProprieteRoute
  '/location-saisonniere': typeof LocationSaisonniereRoute
  '/zones': typeof ZonesRoute
  '/services/housekeeping': typeof ServicesHousekeepingRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conciergerie'
    | '/contact'
    | '/gestion-propriete'
    | '/location-saisonniere'
    | '/zones'
    | '/services/housekeeping'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conciergerie'
    | '/contact'
    | '/gestion-propriete'
    | '/location-saisonniere'
    | '/zones'
    | '/services/housekeeping'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/conciergerie'
    | '/contact'
    | '/gestion-propriete'
    | '/location-saisonniere'
    | '/zones'
    | '/services/housekeeping'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConciergerieRoute: typeof ConciergerieRoute
  ContactRoute: typeof ContactRoute
  GestionProprieteRoute: typeof GestionProprieteRoute
  LocationSaisonniereRoute: typeof LocationSaisonniereRoute
  ZonesRoute: typeof ZonesRoute
  ServicesHousekeepingRoute: typeof ServicesHousekeepingRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conciergerie': {
      id: '/conciergerie'
      path: '/conciergerie'
      fullPath: '/conciergerie'
      preLoaderRoute: typeof ConciergerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestion-propriete': {
      id: '/gestion-propriete'
      path: '/gestion-propriete'
      fullPath: '/gestion-propriete'
      preLoaderRoute: typeof GestionProprieteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location-saisonniere': {
      id: '/location-saisonniere'
      path: '/location-saisonniere'
      fullPath: '/location-saisonniere'
      preLoaderRoute: typeof LocationSaisonniereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/housekeeping': {
      id: '/services/housekeeping'
      path: '/services/housekeeping'
      fullPath: '/services/housekeeping'
      preLoaderRoute: typeof ServicesHousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConciergerieRoute: ConciergerieRoute,
  ContactRoute: ContactRoute,
  GestionProprieteRoute: GestionProprieteRoute,
  LocationSaisonniereRoute: LocationSaisonniereRoute,
  ZonesRoute: ZonesRoute,
  ServicesHousekeepingRoute: ServicesHousekeepingRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
