/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is generated by TanStack Router. It is kept in sync here so the
// production build cannot ship with stale route metadata.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as GestionProprieteRouteImport } from './routes/gestion-propriete'
import { Route as ConciergerieRouteImport } from './routes/conciergerie'
import { Route as LocationSaisonniereRouteImport } from './routes/location-saisonniere'
import { Route as HousekeepingRouteImport } from './routes/services/housekeeping'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const ContactRoute = ContactRouteImport.update({ id: '/contact', path: '/contact', getParentRoute: () => rootRouteImport } as any)
const ServicesRoute = ServicesRouteImport.update({ id: '/services', path: '/services', getParentRoute: () => rootRouteImport } as any)
const ZonesRoute = ZonesRouteImport.update({ id: '/zones', path: '/zones', getParentRoute: () => rootRouteImport } as any)
const GestionProprieteRoute = GestionProprieteRouteImport.update({ id: '/gestion-propriete', path: '/gestion-propriete', getParentRoute: () => rootRouteImport } as any)
const ConciergerieRoute = ConciergerieRouteImport.update({ id: '/conciergerie', path: '/conciergerie', getParentRoute: () => rootRouteImport } as any)
const LocationSaisonniereRoute = LocationSaisonniereRouteImport.update({ id: '/location-saisonniere', path: '/location-saisonniere', getParentRoute: () => rootRouteImport } as any)
const HousekeepingRoute = HousekeepingRouteImport.update({ id: '/services/housekeeping', path: '/housekeeping', getParentRoute: () => ServicesRoute } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/zones': typeof ZonesRoute
  '/gestion-propriete': typeof GestionProprieteRoute
  '/conciergerie': typeof ConciergerieRoute
  '/location-saisonniere': typeof LocationSaisonniereRoute
  '/services/housekeeping': typeof HousekeepingRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/zones': typeof ZonesRoute
  '/gestion-propriete': typeof GestionProprieteRoute
  '/conciergerie': typeof ConciergerieRoute
  '/location-saisonniere': typeof LocationSaisonniereRoute
  '/services/housekeeping': typeof HousekeepingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByTo
  id: keyof FileRoutesById
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  ZonesRoute: typeof ZonesRoute
  GestionProprieteRoute: typeof GestionProprieteRoute
  ConciergerieRoute: typeof ConciergerieRoute
  LocationSaisonniereRoute: typeof LocationSaisonniereRoute
  HousekeepingRoute: typeof HousekeepingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/contact': { id: '/contact'; path: '/contact'; fullPath: '/contact'; preLoaderRoute: typeof ContactRouteImport; parentRoute: typeof rootRouteImport }
    '/services': { id: '/services'; path: '/services'; fullPath: '/services'; preLoaderRoute: typeof ServicesRouteImport; parentRoute: typeof rootRouteImport }
    '/zones': { id: '/zones'; path: '/zones'; fullPath: '/zones'; preLoaderRoute: typeof ZonesRouteImport; parentRoute: typeof rootRouteImport }
    '/gestion-propriete': { id: '/gestion-propriete'; path: '/gestion-propriete'; fullPath: '/gestion-propriete'; preLoaderRoute: typeof GestionProprieteRouteImport; parentRoute: typeof rootRouteImport }
    '/conciergerie': { id: '/conciergerie'; path: '/conciergerie'; fullPath: '/conciergerie'; preLoaderRoute: typeof ConciergerieRouteImport; parentRoute: typeof rootRouteImport }
    '/location-saisonniere': { id: '/location-saisonniere'; path: '/location-saisonniere'; fullPath: '/location-saisonniere'; preLoaderRoute: typeof LocationSaisonniereRouteImport; parentRoute: typeof rootRouteImport }
    '/services/housekeeping': { id: '/services/housekeeping'; path: '/services/housekeeping'; fullPath: '/services/housekeeping'; preLoaderRoute: typeof HousekeepingRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren({ HousekeepingRoute })

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  ContactRoute,
  ServicesRoute: ServicesRouteWithChildren,
  ZonesRoute,
  GestionProprieteRoute,
  ConciergerieRoute,
  LocationSaisonniereRoute,
  HousekeepingRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
